--- #YAML:1.0
name:               Test-Reporter-Transport-Net-SMTP-SSL
version:            0.1.1
abstract:           SMTP over SSL transport for Test::Reporter
author:
    - Theodore Robert Campbell Jr <trcjr@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Net::SMTP::SSL:  0
    Test::More:      0
    Test::Reporter:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
